# PDC Project
## Encoding-Viterbi decoding over an AWGN + erasure channel
### How to use :
Replace '80char.txt' below with the file to send.

Sequentially run all the cells.

In [44]:
# Imports

%load_ext autoreload
%autoreload 2
from encoder_utils import Encoder
from decoder_utils import Decoder
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [45]:
# Parameters

L = 10 # Number of previous bits used
N = 18 # Number of output bits per input bit

In [46]:
# filenames

original_file  = '80char.txt'                             # << Insert here the name of the file to send
encoded_file   = 'encoded.txt'
channel_output = 'channel_output.txt'
decoded_file   = 'decoded.txt'

In [47]:
# Encoding-Decoding generator matrix (used by both the encoder and the decoder)

def generate_generator_matrix():
    """
    Creates the generator matrix.
    We make sure that for each generator_polynomial (A line of the generator matrix), the first and the last bits are set to 1
    This is because we at least want b_i and b_{i-L} to be used to use the whole range L. The remaining coefficients are chosen
    at random as no method exists to optimally pick them deterministically.
    """
    generator_matrix = np.random.choice([0, 1], size=(N, L+1))
    generator_matrix[:,0] = 1
    generator_matrix[:,L] = 1
    return generator_matrix
generator_matrix = generate_generator_matrix()
print('Generator matrix :\n', generator_matrix)

Generator matrix :
 [[1 0 0 1 1 1 0 1 1 0 1]
 [1 1 0 1 0 1 1 0 0 1 1]
 [1 0 1 1 0 1 1 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 0 1]
 [1 0 1 1 0 1 0 0 0 0 1]
 [1 1 1 0 0 1 0 0 0 0 1]
 [1 1 1 0 1 1 1 0 1 0 1]
 [1 0 0 0 1 1 1 1 0 1 1]
 [1 1 0 0 1 1 1 0 1 0 1]
 [1 1 1 0 1 1 0 1 1 0 1]
 [1 1 0 0 0 0 0 1 1 1 1]
 [1 0 1 0 1 1 1 1 0 0 1]
 [1 1 0 1 1 0 0 0 0 1 1]
 [1 0 0 0 0 1 1 0 0 0 1]
 [1 1 1 1 0 0 1 0 0 1 1]
 [1 1 1 1 1 1 0 0 1 0 1]
 [1 1 1 0 0 1 0 1 0 1 1]
 [1 0 0 1 1 0 0 0 0 1 1]]


In [48]:
# Instantiate the encoder and decoder

encoder = Encoder(input_file=original_file,  output_file=encoded_file, generator_matrix=generator_matrix, verbose=False)
decoder = Decoder(input_file=channel_output, output_file=decoded_file, generator_matrix=generator_matrix, verbose=False)

In [49]:
# Encode

encoder.encode()

Original file : b'Hello world, planet, solar system all the way to A-Centuri and the entire galaxy'

Hello world, planet, solar system all the way to A-Centuri and the entire galaxy
Total number of bits used : 23040


In [50]:
# AWGN + erasure channel

!python client.py --input_file {encoded_file} --output_file {channel_output} --srv_hostname iscsrv72.epfl.ch --srv_port 80

In [51]:
# Decode

decoder.decode()

Compact_values_length : 11520
nb_trellis_sections : 640
Trellis height : 1024
Trellis width  : 641
Decoding ...
bytearray(b'Hello world, planet, solar system all the way to A-Centuri and the entire galaxy')
